config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # resources :users
  # resources :calendars
  resources :bookings

  get 'bookings/date/:param_date', to: 'bookings#show_bookings_by_date', as: 'date_booking'

  get 'calendars/index'
  root 'calendars#index'
end

app/models/booking.rb
class Booking < ApplicationRecord

  belongs_to :user, optional: true
  belongs_to :calendar, optional: true

  validates :title, :start_date, :end_date, :user_id, :calendar_id, presence: true
  validate :end_after_start

  def start_time
    start_date
  end

  def end_time
    end_date
  end

  private

  def end_after_start
    return if end_date.blank? || start_date.blank?
    return errors.add(:end_date, 'must be after the start date') unless end_date > start_date
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  respond_to :html, :json
  before_action :authenticate_user!
  before_action :check_record_exists?, only: [:create, :edit]
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
    @date = Date.parse(params[:date])
  end

  # GET /bookings/date/28012020
  def show_bookings_by_date
    @paramDate = Date.parse(params[:param_date])
    @bookings = Booking.where('start_date::date <= ? AND end_date::date >= ?', @paramDate, @paramDate)

    respond_with(@paramDate, @bookings) do |format|
      format.html { render :index }
    end
  end

  # GET /bookings/1/edit
  def edit
    @paramDate = Date.parse(params[:start_date])

  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_booking
    @booking = Booking.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def booking_params
    params.require(:booking).permit(:title, :start_date, :end_date, :user_id, :calendar_id)
  end

  def check_record_exists?
    if Booking.where('calendar_id = ? AND start_date > ? AND end_date < ?', params[:calendar_id], params[:start_date], params[:start_date]).exists?
      render json: { error: 'Room already reserved.' }
    end
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_with(model: booking, local: true) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% booking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date, selected: @date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.datetime_select :end_date, selected: @date %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, User.order(:name),:id,:name, include_blank: true %>
  </div>

  <div class="field">
    <%= form.label :calendar_id %>
    <%= form.collection_select :calendar_id, Calendar.order(:name),:id,:name, include_blank: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', date_booking_path(@paramDate) %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<%= calendar number_of_days: 1 do |date| %>
  <%= @paramDate.strftime("%D") %>

  <table>
    <thead>
    <tr>
      <th>Title</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Who</th>
      <th>Room</th>
      <th colspan="2"></th>
    </tr>
    </thead>

    <tbody>
      <% @bookings.each do |booking| %>
        <tr>
          <td><%= booking.title %></td>
          <td><%= booking.start_date.strftime("%H:%M") %></td>
          <td><%= booking.end_date.strftime("%H:%M") %></td>
          <td><%= booking.user_id %></td>
          <td><%= booking.calendar.name %></td>
          <td><%= link_to 'Edit', edit_booking_path(booking, 'start_date' => @paramDate) %></td>
          <td><%= link_to 'Delete', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>



<br>

<%= link_to 'Back', calendars_index_path %>

app/views/bookings/index.js.erb
$("#bookings_calendar").html("<%= escape_javascript render(partial: "calendar", locals: {paramDate: @paramDate}) %>");

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', calendars_index_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @booking.title %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @booking.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @booking.end_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @booking.user_id %>
</p>

<p>
  <strong>Calendar:</strong>
  <%= @booking.calendar_id %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', calendars_index_path %>