config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # resources :users
  # resources :calendars
  resources :bookings

  get 'bookings/date/:param_date', to: 'bookings#show_bookings_by_date', as: 'date_booking'

  get 'calendars/index'
  root 'calendars#index'
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  has_many :bookings
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  # before_action :set_calendar, only: [:show, :edit, :update, :destroy]
  before_action :set_calendar, only: [:show]

  # GET /calendars
  # GET /calendars.json
  def index
    @calendars = Calendar.all
    @bookings = Booking.all
  end

  # # GET /calendars/1
  # # GET /calendars/1.json
  # def show
  # end
  #
  # # GET /calendars/new
  # def new
  #   @calendar = Calendar.new
  # end
  #
  # # GET /calendars/1/edit
  # def edit
  # end
  #
  # # POST /calendars
  # # POST /calendars.json
  # def create
  #   @calendar = Calendar.new(calendar_params)
  #
  #   respond_to do |format|
  #     if @calendar.save
  #       format.html { redirect_to @calendar, notice: 'Calendar was successfully created.' }
  #       format.json { render :show, status: :created, location: @calendar }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @calendar.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # PATCH/PUT /calendars/1
  # # PATCH/PUT /calendars/1.json
  # def update
  #   respond_to do |format|
  #     if @calendar.update(calendar_params)
  #       format.html { redirect_to @calendar, notice: 'Calendar was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @calendar }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @calendar.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # DELETE /calendars/1
  # # DELETE /calendars/1.json
  # def destroy
  #   @calendar.destroy
  #   respond_to do |format|
  #     format.html { redirect_to calendars_url, notice: 'Calendar was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end
  #
  # private
  #   # Use callbacks to share common setup or constraints between actions.
  #   def set_calendar
  #     @calendar = Calendar.find(params[:id])
  #   end
  #
  #   # Only allow a list of trusted parameters through.
  #   def calendar_params
  #     params.require(:calendar).permit(:name, :color_ind, :location)
  #   end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
  def url_for_previous_view
    ->(param, date_range) { link_to raw("&laquo;"), date_booking_path(date_range.first - 1.day, param => date_range.first - 1.day), remote: :true}
  end

  def url_for_next_view
    ->(param, date_range) { link_to raw("&raquo;"), date_booking_path(date_range.last + 1.day, param => date_range.last + 1.day), remote: :true}
  end
end

app/views/calendars/_form.html.erb
<%= form_with(model: calendar, local: true) do |form| %>
  <% if calendar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(calendar.errors.count, "error") %> prohibited this calendar from being saved:</h2>

      <ul>
        <% calendar.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :color_ind %>
    <%= form.text_field :color_ind %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/calendars/edit.html.erb
<h1>Editing Calendar</h1>

<%= render 'form', calendar: @calendar %>

<%= link_to 'Show', @calendar %> |
<%= link_to 'Back', calendars_path %>

app/views/calendars/index.html.erb
  <div class="text-center">
    <h1>View Calendar Bookings</h1>
  </div>

  <div class="container">
    <p id="notice"><%= notice %></p>

    <div class="row">
      <div class="col-lg-12">

        <%= month_calendar events: @bookings do |date, bookings|%>
          <%= link_to date.strftime("%e"), date_booking_path(date, :start_date => date)  %>
          <% if date.strftime("%D") >= DateTime.now.strftime("%D") %>
            <%= link_to '+', new_booking_path(:date => date), class: 'new_booking' %>
          <% end %>

          <% bookings.each do |booking| %>
            <div class="<%= booking.calendar.color_ind if booking.calendar != nil %> booking-block">
              <%= link_to booking.title, booking_path(booking.id)  %>
            </div>
          <% end %>

        <% end %>

      </div>
    </div>
  </div>

app/views/calendars/new.html.erb
<h1>New Calendar</h1>

<%= render 'form', calendar: @calendar %>

<%= link_to 'Back', calendars_path %>

app/views/calendars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @calendar.name %>
</p>

<p>
  <strong>Color ind:</strong>
  <%= @calendar.color_ind %>
</p>

<p>
  <strong>Location:</strong>
  <%= @calendar.location %>
</p>

<%= link_to 'Edit', edit_calendar_path(@calendar) %> |
<%= link_to 'Back', calendars_path %>