config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # resources :users
  # resources :calendars
  resources :bookings

  get 'bookings/date/:param_date', to: 'bookings#show_bookings_by_date', as: 'date_booking'

  get 'calendars/index'
  root 'calendars#index'
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-dark navbar-static-top navbar-expand-md">
  <div class="container">
    <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
    </button>
    <%= link_to "Main Calendar", root_path, class: 'navbar-brand' %>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav mr-auto">
        <li class='nav-item'><%= link_to 'Bookings', bookings_path, class: 'nav-link' %></li>
        </li>
      </ul>
    </div>
    <div class="navbar-text float-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title><%= content_for?(:title) ? yield(:title) : "Rails Booking System" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "A Rails Tech Assignment - Booking System for Meeting Rooms" %>">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <main role="main">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>


  </body>
</html>